openapi: 3.0.0
info:
  title: ABC CRM
  version: 1.0.0
paths:
  /api/login:
    post:
      tags:
        - Login
      summary: User Login
      description: Login User Here
      operationId: authLogin
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: email
                password:
                  type: password
              type: object
          application/json:
            schema: {}
      responses:
        '200':
          description: Login Successfully
          content:
            application/json:
              schema: {}
        '201':
          description: Login Successfully
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
        '404':
          description: Resource Not Found
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema: {}
  /customers:
    get:
      tags:
        - Customers
      summary: Get list of customers
      description: Returns list of customers
      operationId: getCustomerList
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
  /customer:
    post:
      tags:
        - Customers
      summary: Store new Customer
      description: Returns customer data
      operationId: storeCustomer
      requestBody:
        required: true
      responses:
        '201':
          description: Successful operation
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
  /customers/{id}:
    get:
      tags:
        - Customers
      summary: Get Customers information
      description: Returns Customers data
      operationId: getCustomersById
      parameters:
        - name: id
          in: path
          description: Customers id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
    put:
      tags:
        - Customers
      summary: Update existing customers
      description: Returns updated customers data
      operationId: updatecustomers
      parameters:
        - name: id
          in: path
          description: customers id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
      responses:
        '202':
          description: Successful operation
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Resource Not Found
    delete:
      tags:
        - Customers
      summary: Delete existing customers
      description: Deletes a record and returns no content
      operationId: deleteCustomers
      parameters:
        - name: id
          in: path
          description: Customers id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Successful operation
          content:
            application/json:
              schema: {}
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Resource Not Found
  /customers-import:
    post:
      tags:
        - Imposert Customer CSV
      summary: Update existing customers or adding
      description: Deletes a record and returns no content
      operationId: importCustomers
      parameters:
        - name: file
          in: path
          description: file
          required: true
      responses:
        '204':
          description: Successful operation
          content:
            application/json:
              schema: {}
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Resource Not Found
security:
  - []
